## pack=wownero version=1.0.0 source=9f05ca86c04cb252a3c2a159f3c08c3677dbf5dc
extends RefCounted
## GENERATED by such_graphics.style.tokens from the style pack -- DO NOT EDIT BY HAND.
## pack: wownero

const BG := Color(0.0392, 0.0353, 0.0941)
const INK := Color(0.9922, 0.9647, 0.8902)
const MUTED := Color(0.5412, 0.5412, 0.6902)
const ACCENT := Color(0.9608, 0.7725, 0.0941)
const SURFACE := Color(0.0902, 0.0706, 0.2118)
const ACCENT_HI := Color(1.0000, 0.8784, 0.4000)
const WOW := Color(1.0000, 0.1765, 0.6078)
const PARTICLE := Color(0.7882, 0.7137, 1.0000)

const FS_TITLE := 124
const FS_SUBHEAD := 54
const FS_BODY := 34
const FS_CAPTION := 22

const DUR_GROW_MS := 460
const DUR_FADE_MS := 240
const DUR_BOUNCE_MS := 380

const SHAPE_CORNER_SM := 4
const SHAPE_CORNER_MD := 8
const SHAPE_CORNER_LG := 12
const SHAPE_TOUCH_MIN := 48

const GRADE_TONEMAP := "filmic"
const GRADE_EXPOSURE := 1.08
const GRADE_CONTRAST := 1.05
const GRADE_SATURATION := 1.18
const GRADE_GLOW := 1.5
const GRADE_VIGNETTE := 0.4
const GRADE_GRAIN := 0.25

const LIGHT_KEY_COLOR := Color(0.9922, 0.9647, 0.8902)
const LIGHT_KEY_ENERGY := 1.6
const LIGHT_KEY_ANGLE := Vector3(-40, -25, 0)
const LIGHT_FILL_COLOR := Color(0.5412, 0.5412, 0.6902)
const LIGHT_FILL_ENERGY := 0.45
const LIGHT_RIM_COLOR := Color(0.9608, 0.7725, 0.0941)
const LIGHT_RIM_ENERGY := 1.5

const ENV_BG := Color(0.0392, 0.0353, 0.0941)
const ENV_AMBIENT := 0.5
const ENV_FOG := 0.12
const ENV_FOG_COLOR := Color(0.0902, 0.0706, 0.2118)
const ENV_PLINTH_COLOR := Color(0.0902, 0.0706, 0.2118)

const CAMERA_FOV := 52
const CAMERA_MOVE := "crane-up"
const CAMERA_SPEED := 0.4
const CAMERA_INTENSITY := 1.0
